export const AWSProducts = [
    "Amazon API Gateway",
    "Amazon AppFlow",
    "Amazon AppStream",
    "Amazon Athena",
    "Amazon Bedrock",
    "Amazon Chime",
    "Amazon CloudFront",
    "Amazon CloudSearch",
    "Amazon CodeWhisperer",
    "Amazon Cognito",
    "Amazon Comprehend",
    "Amazon Connect",
    "Amazon DataZone",
    "Amazon Detective",
    "Amazon DevOps Guru",
    "Amazon DocumentDB (with MongoDB compatibility)",
    "Amazon DynamoDB",
    "Amazon EC2",
    "Amazon EC2 Container Registry (ECR)",
    "Amazon Elastic Compute Cloud",
    "Amazon Elastic Container Registry Public",
    "Amazon Elastic Container Service",
    "Amazon Elastic Container Service for Kubernetes",
    "Amazon Elastic File System",
    "Amazon Elastic MapReduce",
    "Amazon Elastic Transcoder",
    "Amazon ElastiCache",
    "Amazon FSx",
    "Amazon Glacier",
    "Amazon GuardDuty",
    "Amazon HealthLake",
    "Amazon Inspector",
    "Amazon Interactive Video Service",
    "Amazon Kendra",
    "Amazon Keyspaces (for Apache Cassandra)",
    "Amazon Kinesis",
    "Amazon Kinesis Analytics",
    "Amazon Kinesis Firehose",
    "Amazon Lambda",
    "Amazon Lex",
    "Amazon Lightsail",
    "Amazon Location Service",
    "Amazon Machine Learning",
    "Amazon Macie",
    "Amazon Managed Blockchain",
    "Amazon Managed Grafana",
    "Amazon Managed Service for Prometheus",
    "Amazon Managed Streaming for Apache Kafka",
    "Amazon Managed Workflows for Apache Airflow",
    "Amazon Mechanical Turk",
    "Amazon Mechanical Turk Worker Rewards",
    "Amazon MemoryDB",
    "Amazon MQ",
    "Amazon Neptune",
    "Amazon Omics",
    "Amazon OpenSearch Service",
    "Amazon Personalize",
    "Amazon Polly",
    "Amazon Q",
    "Amazon Quantum Ledger Database",
    "Amazon QuickSight",
    "Amazon RDS",
    "Amazon Redshift",
    "Amazon Registrar",
    "Amazon Rekognition",
    "Amazon Relational Database Service",
    "Amazon Route 53",
    "Amazon S3",
    "Amazon S3 Glacier Deep Archive",
    "Amazon SageMaker",
    "Amazon Security Lake",
    "Amazon Simple Email Service",
    "Amazon Simple Notification Service",
    "Amazon Simple Queue Service",
    "Amazon Simple Storage Service",
    "Amazon Simple Workflow Service",
    "Amazon SimpleDB",
    "Amazon Textract",
    "Amazon Timestream",
    "Amazon Transcribe",
    "Amazon Translate",
    "Amazon Verified Permissions",
    "Amazon Virtual Private Cloud",
    "Amazon VPC",
    "Amazon WorkDocs",
    "Amazon WorkSpaces",
    "Amazon WorkSpaces Web",
    "AmazonCloudWatch",
    "AmazonWorkMail",
    "AWS Amplify",
    "AWS App Runner",
    "AWS AppSync",
    "AWS Application Migration Service",
    "AWS Audit Manager",
    "AWS Backup",
    "AWS Billing Conductor",
    "AWS Budgets",
    "AWS Certificate Manager",
    "AWS Cloud Map",
    "AWS Cloud WAN",
    "AWS CloudFormation",
    "AWS CloudHSM",
    "AWS CloudShell",
    "AWS CloudTrail",
    "AWS CodeArtifact",
    "AWS CodeBuild",
    "AWS CodeCommit",
    "AWS CodePipeline",
    "AWS Compute Optimizer",
    "AWS Config",
    "AWS Cost Explorer",
    "AWS Data Pipeline",
    "AWS Data Transfer",
    "AWS Database Migration Service",
    "AWS DataSync",
    "AWS DeepRacer",
    "AWS Device Farm",
    "AWS Direct Connect",
    "AWS Directory Service",
    "AWS Elemental MediaConnect",
    "AWS Elemental MediaConvert",
    "AWS Elemental MediaLive",
    "AWS Elemental MediaStore",
    "AWS End User Messaging",
    "AWS Firewall Manager",
    "AWS Global Accelerator",
    "AWS Glue",
    "AWS HealthImaging",
    "AWS Identity and Access Management Access Analyzer",
    "AWS IoT",
    "AWS IoT Device Defender",
    "AWS IoT Device Management",
    "AWS IoT Events",
    "AWS IoT TwinMaker",
    "AWS Key Management Service",
    "AWS Lambda",
    "AWS Migration Hub Refactor Spaces",
    "AWS Network Firewall",
    "AWS Payment Cryptography",
    "AWS Route 53 Application Recovery Controller",
    "AWS Secrets Manager",
    "AWS Security Hub",
    "AWS Service Catalog",
    "AWS Shield",
    "AWS Skill Builder Individual",
    "AWS Step Functions",
    "AWS Storage Gateway",
    "AWS Support (Business)",
    "AWS Support (Developer)",
    "AWS Support (Enterprise)",
    "AWS Premium Support",
    "AWS Systems Manager",
    "AWS Telco Network Builder",
    "AWS Transfer Family",
    "AWS WAF",
    "AWS X-Ray",
    "CloudWatch Events",
    "CodeBuild",
    "Contact Lens for Amazon Connect",
    "DynamoDB Accelerator (DAX)",
    "Elastic Load Balancing",
    "Savings Plans for AWS Compute usage",
    "Savings Plans for AWS Machine Learning"
];
