
export const productIconMapping = {
    "Amazon API Gateway": "ArchitectureServiceAmazonAPIGateway",
    "Amazon AppFlow": "ArchitectureServiceAmazonAppFlow",
    "Amazon AppStream": "ArchitectureServiceAmazonAppStream2",
    "Amazon Athena": "ArchitectureServiceAmazonAthena",
    "Amazon Bedrock": "ArchitectureServiceAmazonBedrock",
    "Amazon Chime": "ArchitectureServiceAmazonChime",
    "Amazon CloudFront": "ArchitectureServiceAmazonCloudFront",
    "Amazon CloudSearch": "ArchitectureServiceAmazonCloudSearch",
    "Amazon CodeWhisperer": "ArchitectureServiceAmazonCodeWhisperer",
    "Amazon Cognito": "ArchitectureServiceAmazonCognito",
    "Amazon Comprehend": "ArchitectureServiceAmazonComprehend",
    "Amazon Connect": "ArchitectureServiceAmazonConnect",
    "Amazon DataZone": "ArchitectureServiceAmazonDataZone",
    "Amazon Detective": "ArchitectureServiceAmazonDetective",
    "Amazon DevOps Guru": "ArchitectureServiceAmazonDevOpsGuru",
    "Amazon DocumentDB (with MongoDB compatibility)": "ArchitectureServiceAmazonDocumentDB",
    "Amazon DynamoDB": "ArchitectureServiceAmazonDynamoDB",
    "Amazon EC2": "ArchitectureServiceAmazonEC2",
    "Amazon EC2 Container Registry (ECR)": "ArchitectureServiceAmazonElasticContainerRegistry",
    "Amazon Elastic Compute Cloud": "ArchitectureServiceAmazonEC2",
    "Amazon Elastic Container Registry Public": "ArchitectureServiceAmazonElasticContainerRegistry",
    "Amazon Elastic Container Service": "ArchitectureServiceAmazonElasticContainerService",
    "Amazon Elastic Container Service for Kubernetes": "ArchitectureServiceAmazonElasticKubernetesService",
    "Amazon Elastic File System": "ArchitectureServiceAmazonEFS",
    "Amazon Elastic MapReduce": "ArchitectureServiceAmazonEMR",
    "Amazon Elastic Transcoder": "ArchitectureServiceAmazonElasticTranscoder",
    "Amazon ElastiCache": "ArchitectureServiceAmazonElastiCache",
    "Amazon FSx": "ArchitectureServiceAmazonFSx",
    "Amazon Glacier": "ArchitectureServiceAmazonSimpleStorageServiceGlacier",
    "Amazon GuardDuty": "ArchitectureServiceAmazonGuardDuty",
    "Amazon HealthLake": "ArchitectureServiceAWSHealthLake",
    "Amazon Inspector": "ArchitectureServiceAmazonInspector",
    "Amazon Interactive Video Service": "ArchitectureServiceAmazonInteractiveVideoService",
    "Amazon Kendra": "ArchitectureServiceAmazonKendra",
    "Amazon Keyspaces (for Apache Cassandra)": "ArchitectureServiceAmazonKeyspaces",
    "Amazon Kinesis": "ArchitectureServiceAmazonKinesis",
    "Amazon Kinesis Analytics": "ArchitectureServiceAmazonManagedServiceforApacheFlink",
    "Amazon Kinesis Firehose": "ResourceAmazonDataFirehose",
    "Amazon Lambda": "ArchitectureServiceAWSLambda",
    "Amazon Lex": "ArchitectureServiceAmazonLex",
    "Amazon Lightsail": "ArchitectureServiceAmazonLightsail",
    "Amazon Location Service": "ArchitectureServiceAmazonLocationService",
    "Amazon Machine Learning": "ArchitectureServiceAmazonSageMaker",
    "Amazon Macie": "ArchitectureServiceAmazonMacie",
    "Amazon Managed Blockchain": "ArchitectureServiceAmazonManagedBlockchain",
    "Amazon Managed Grafana": "ArchitectureServiceAmazonManagedGrafana",
    "Amazon Managed Service for Prometheus": "ArchitectureServiceAmazonManagedServiceforPrometheus",
    "Amazon Managed Streaming for Apache Kafka": "ArchitectureServiceAmazonManagedStreamingforApacheKafka",
    "Amazon Managed Workflows for Apache Airflow": "ArchitectureServiceAmazonManagedWorkflowsforApacheAirflow",
    "Amazon Mechanical Turk": "ArchitectureServiceAWSToolsandSDKs",
    "Amazon MemoryDB": "ArchitectureServiceAmazonMemoryDB",
    "Amazon MQ": "ArchitectureServiceAmazonMQ",
    "Amazon Neptune": "ArchitectureServiceAmazonNeptune",
    "Amazon Omics": "ArchitectureServiceAWSHealthOmics",
    "Amazon OpenSearch Service": "ArchitectureServiceAmazonOpenSearchService",
    "Amazon Personalize": "ArchitectureServiceAmazonPersonalize",
    "Amazon Polly": "ArchitectureServiceAmazonPolly",
    "Amazon Q": "ArchitectureServiceAmazonQ",
    "Amazon Quantum Ledger Database": "ArchitectureServiceAmazonQuantumLedgerDatabase",
    "Amazon QuickSight": "ArchitectureServiceAmazonQuickSight",
    "Amazon RDS": "ArchitectureServiceAmazonRDS",
    "Amazon Redshift": "ArchitectureServiceAmazonRedshift",
    "Amazon Registrar": "ArchitectureServiceAmazonRoute53",
    "Amazon Rekognition": "ArchitectureServiceAmazonRekognition",
    "Amazon Relational Database Service": "ArchitectureServiceAmazonRDS",
    "Amazon Route 53": "ArchitectureServiceAmazonRoute53",
    "Amazon S3": "ArchitectureServiceAmazonSimpleStorageService",
    "Amazon S3 Glacier Deep Archive": "ResourceAmazonSimpleStorageServiceS3GlacierDeepArchive",
    "Amazon SageMaker": "ArchitectureServiceAmazonSageMaker",
    "Amazon Security Lake": "ArchitectureServiceAmazonSecurityLake",
    "Amazon Simple Email Service": "ArchitectureServiceAmazonSimpleEmailService",
    "Amazon Simple Notification Service": "ArchitectureServiceAmazonSimpleNotificationService",
    "Amazon Simple Queue Service": "ArchitectureServiceAmazonSimpleQueueService",
    "Amazon Simple Storage Service": "ArchitectureServiceAmazonSimpleStorageService",
    "Amazon Simple Workflow Service": "ArchitectureServiceAWSExpressWorkflows",
    "Amazon SimpleDB": "ResourceDatabase",
    "Amazon Textract": "ArchitectureServiceAmazonTextract",
    "Amazon Timestream": "ArchitectureServiceAmazonTimestream",
    "Amazon Transcribe": "ArchitectureServiceAmazonTranscribe",
    "Amazon Translate": "ArchitectureServiceAmazonTranslate",
    "Amazon Verified Permissions": "ArchitectureServiceAmazonVerifiedPermissions",
    "Amazon Virtual Private Cloud": "ArchitectureServiceAmazonVirtualPrivateCloud",
    "Amazon VPC": "ArchitectureServiceAmazonVirtualPrivateCloud",
    "Amazon WorkDocs": "ArchitectureServiceAmazonWorkDocs",
    "Amazon WorkSpaces": "ArchitectureServiceAmazonWorkSpacesFamily",
    "Amazon WorkSpaces Web": "ResourceAmazonWorkSpacesFamilyAmazonWorkSpacesSecureBrowser",
    "AmazonCloudWatch": "ArchitectureServiceAmazonCloudWatch",
    "AmazonWorkMail": "ArchitectureServiceAmazonWorkMail",
    "AWS Amplify": "ArchitectureServiceAWSAmplify",
    "AWS App Runner": "ArchitectureServiceAWSAppRunner",
    "AWS AppSync": "ArchitectureServiceAWSAppSync",
    "AWS Application Migration Service": "ArchitectureServiceAWSApplicationMigrationService",
    "AWS Audit Manager": "ArchitectureServiceAWSAuditManager",
    "AWS Backup": "ArchitectureServiceAWSBackup",
    "AWS Billing Conductor": "ArchitectureServiceAWSBillingConductor",
    "AWS Budgets": "ArchitectureServiceAWSBudgets",
    "AWS Certificate Manager": "ArchitectureServiceAWSCertificateManager",
    "AWS Cloud Map": "ArchitectureServiceAWSCloudMap",
    "AWS Cloud WAN": "ArchitectureServiceAWSCloudWAN",
    "AWS CloudFormation": "ArchitectureServiceAWSCloudFormation",
    "AWS CloudHSM": "ArchitectureServiceAWSCloudHSM",
    "AWS CloudShell": "ArchitectureServiceAWSCloudShell",
    "AWS CloudTrail": "ArchitectureServiceAWSCloudTrail",
    "AWS CodeArtifact": "ArchitectureServiceAWSCodeArtifact",
    "AWS CodeBuild": "ArchitectureServiceAWSCodeBuild",
    "AWS CodeCommit": "ArchitectureServiceAWSCodeCommit",
    "AWS CodePipeline": "ArchitectureServiceAWSCodePipeline",
    "AWS Compute Optimizer": "ArchitectureServiceAWSComputeOptimizer",
    "AWS Config": "ArchitectureServiceAWSConfig",
    "AWS Cost Explorer": "ArchitectureServiceAWSCostExplorer",
    "AWS Data Pipeline": "ArchitectureServiceAWSDataTransferTerminal",
    "AWS Data Transfer": "ArchitectureServiceAWSDataTransferTerminal",
    "AWS Database Migration Service": "ArchitectureServiceAWSDatabaseMigrationService",
    "AWS DataSync": "ArchitectureServiceAWSDataSync",
    "AWS DeepRacer": "ArchitectureServiceAWSDeepRacer",
    "AWS Device Farm": "ArchitectureServiceAWSDeviceFarm",
    "AWS Direct Connect": "ArchitectureServiceAWSDirectConnect",
    "AWS Directory Service": "ArchitectureServiceAWSDirectoryService",
    "AWS Elemental MediaConnect": "ArchitectureServiceAWSElementalMediaConnect",
    "AWS Elemental MediaConvert": "ArchitectureServiceAWSElementalMediaConvert",
    "AWS Elemental MediaLive": "ArchitectureServiceAWSElementalMediaLive",
    "AWS Elemental MediaStore": "ArchitectureServiceAWSElementalMediaStore",
    "AWS End User Messaging": "ArchitectureServiceAWSEndUserMessaging",
    "AWS Firewall Manager": "ArchitectureServiceAWSFirewallManager",
    "AWS Global Accelerator": "ArchitectureServiceAWSGlobalAccelerator",
    "AWS Glue": "ArchitectureServiceAWSGlue",
    "AWS HealthImaging": "ArchitectureServiceAWSHealthImaging",
    "AWS Identity and Access Management Access Analyzer": "ResourceAWSIdentityAccessManagementIAMAccessAnalyzer",
    "AWS Identity and Access Management": "ArchitectureServiceAWSIdentityandAccessManagement",
    "AWS IoT": "ArchitectureServiceAWSIoTCore",
    "AWS IoT Device Defender": "ArchitectureServiceAWSIoTDeviceDefender",
    "AWS IoT Device Management": "ArchitectureServiceAWSIoTDeviceManagement",
    "AWS IoT Events": "ArchitectureServiceAWSIoTEvents",
    "AWS IoT TwinMaker": "ArchitectureServiceAWSIoTTwinMaker",
    "AWS Key Management Service": "ArchitectureServiceAWSKeyManagementService",
    "AWS Lambda": "ArchitectureServiceAWSLambda",
    "AWS Migration Hub Refactor Spaces": "ResourceAWSMigrationHubRefactorSpacesApplications",
    "AWS Network Firewall": "ArchitectureServiceAWSNetworkFirewall",
    "AWS Payment Cryptography": "ArchitectureServiceAWSPaymentCryptography",
    "AWS Route 53 Application Recovery Controller": "ArchitectureServiceAmazonApplicationRecoveryController",
    "AWS Secrets Manager": "ArchitectureServiceAWSSecretsManager",
    "AWS Security Hub": "ArchitectureServiceAWSSecurityHub",
    "AWS Service Catalog": "ArchitectureServiceAWSServiceCatalog",
    "AWS Shield": "ArchitectureServiceAWSShield",
    "AWS Step Functions": "ArchitectureServiceAWSStepFunctions",
    "AWS Storage Gateway": "ArchitectureServiceAWSStorageGateway",
    "AWS Support (Business)": "ArchitectureServiceAWSSupport",
    "AWS Support (Developer)": "ArchitectureServiceAWSSupport",
    "AWS Support (Enterprise)": "ArchitectureServiceAWSSupport",
    "AWS Premium Support": "ArchitectureServiceAWSSupport",
    "AWS Systems Manager": "ArchitectureServiceAWSSystemsManager",
    "AWS Telco Network Builder": "ArchitectureServiceAWSTelcoNetworkBuilder",
    "AWS Transfer Family": "ArchitectureServiceAWSTransferFamily",
    "AWS WAF": "ArchitectureServiceAWSWAF",
    "AWS X-Ray": "ArchitectureServiceAWSXRay",
    "CloudWatch Events": "ResourceAmazonCloudWatchEventEventBased",
    "CodeBuild": "ArchitectureServiceAWSCodeBuild",
    "Contact Lens for Amazon Connect": "ArchitectureServiceAmazonConnect",
    "DynamoDB Accelerator (DAX)": "ResourceAmazonDynamoDBAmazonDynamoDBAccelerator",
    "Elastic Load Balancing": "ArchitectureServiceElasticLoadBalancing"
};
